language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
  yarn: true
before_install:
  - export TZ='Asia/Shanghai' # 设置时区
install:
  - npm i -g vuepress
  - yarn install
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  target-branch: master
  verbose: true
  keep-history: true
  name: vxhly
  email: pengchengou@gmail.com
  on:
    branch: gh-pages
branches:
  only:
    - gh-pages
